<template>
    <div class="page-narrow">
        <h1>配置文件</h1>
        <p>aos4n-web的配置位于config.json的web节，具体字段说明如下：</p>
        <table>
            <thead>
                <tr>
                    <th>名称</th>
                    <th>类型</th>
                    <th>默认值</th>
                    <th>说明</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>port</td>
                    <td>number</td>
                    <td>3000</td>
                    <td>如果指定了环境变量aos4nWebPort，则优先使用环境变量的值</td>
                </tr>
                <tr>
                    <td>enableStatic</td>
                    <td>boolean</td>
                    <td>false</td>
                    <td>是否开启静态内容支持，如果确定不需要静态内容支持，可以保持此选项关闭，可以提升性能，开启后，会使用public目录作为静态文件目录</td>
                </tr>
                <tr>
                    <td>enableCors</td>
                    <td>boolean</td>
                    <td>false</td>
                    <td>是否开启跨域</td>
                </tr>
                <tr>
                    <td>corsOptions</td>
                    <td>CorsOptions</td>
                    <td>new CorsOptions()</td>
                    <td>跨域选项，参考下面的CorsOptions</td>
                </tr>
                <tr>
                    <td>koaBodyOptions</td>
                    <td>KoaBodyOptions</td>
                    <td>new KoaBodyOptions()</td>
                    <td>
                        表单选项，该配置比较复杂，可以参考原项目说明
                        <a
                            href="https://github.com/dlau/koa-body"
                        >https://github.com/dlau/koa-body</a>
                    </td>
                </tr>
            </tbody>
        </table>

        <p>
            CorsOptions，具体说明请参考
            <a href="https://github.com/zadzbw/koa2-cors">koa2-cors</a>
        </p>
        <table>
            <thead>
                <tr>
                    <th>名称</th>
                    <th>类型</th>
                    <th>默认值</th>
                    <th>说明</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>origin</td>
                    <td>string</td>
                    <td>undefined</td>
                    <td></td>
                </tr>
                <tr>
                    <td>exposeHeaders</td>
                    <td>string[]</td>
                    <td>undefined</td>
                    <td></td>
                </tr>
                <tr>
                    <td>maxAge</td>
                    <td>number</td>
                    <td>undefined</td>
                    <td></td>
                </tr>
                <tr>
                    <td>credentials</td>
                    <td>boolean</td>
                    <td>undefined</td>
                    <td></td>
                </tr>
                <tr>
                    <td>allowMethods</td>
                    <td>string[]</td>
                    <td>undefined</td>
                    <td></td>
                </tr>
                <tr>
                    <td>allowHeaders</td>
                    <td>string[]</td>
                    <td>undefined</td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    </div>
</template>